//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AllShowMVCApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLOYEE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EMPLOYEE()
        {
            this.ADVERTISEMENTs = new HashSet<ADVERTISEMENT>();
            this.ANNOUNCEMENTs = new HashSet<ANNOUNCEMENT>();
            this.AUTHORITies = new HashSet<AUTHORITY>();
            this.SHOPs = new HashSet<SHOP>();
        }
    
        public int empno { get; set; }
        public string empname { get; set; }
        public string empaccount { get; set; }
        public string emppwd { get; set; }
        public string EMPEMAIL { get; set; }
        public string empsex { get; set; }
        public System.DateTime empbirth { get; set; }
        public string emptel { get; set; }
        public System.DateTime hiredate { get; set; }
        public Nullable<System.DateTime> leavedate { get; set; }
        public string empaccountstate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ADVERTISEMENT> ADVERTISEMENTs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ANNOUNCEMENT> ANNOUNCEMENTs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AUTHORITY> AUTHORITies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SHOP> SHOPs { get; set; }
    }
}
