//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCStudy.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AllShowEntities : DbContext
    {
        public AllShowEntities()
            : base("name=AllShowEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ADVERTISEMENT> ADVERTISEMENTs { get; set; }
        public virtual DbSet<ANNOUNCEMENT> ANNOUNCEMENTs { get; set; }
        public virtual DbSet<AUTHORITY> AUTHORITies { get; set; }
        public virtual DbSet<AUTHORITYFUNCTION> AUTHORITYFUNCTIONs { get; set; }
        public virtual DbSet<EMPLOYEE> EMPLOYEEs { get; set; }
        public virtual DbSet<FAVORITESHOPLIST> FAVORITESHOPLISTs { get; set; }
        public virtual DbSet<MEMBER> MEMBERs { get; set; }
        public virtual DbSet<MEMBERLIST> MEMBERLISTs { get; set; }
        public virtual DbSet<Message> Messages { get; set; }
        public virtual DbSet<ORDERLIST> ORDERLISTs { get; set; }
        public virtual DbSet<PRODUCT> PRODUCTs { get; set; }
        public virtual DbSet<PRODUCTCLASS> PRODUCTCLASSes { get; set; }
        public virtual DbSet<SHCLASS> SHCLASSes { get; set; }
        public virtual DbSet<SHOP> SHOPs { get; set; }
        public virtual DbSet<SHOPORDER> SHOPORDERs { get; set; }
    }
}
