//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCStudy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SHOPORDER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SHOPORDER()
        {
            this.ORDERLISTs = new HashSet<ORDERLIST>();
        }
    
        public int shoporderNo { get; set; }
        public int orderNo { get; set; }
        public int shNo { get; set; }
        public double orderPrice { get; set; }
        public Nullable<System.DateTime> referredToDate { get; set; }
        public Nullable<System.DateTime> transactionDate { get; set; }
        public string orderState { get; set; }
        public string recipientName { get; set; }
        public string recipientTel { get; set; }
        public string recipientAddress { get; set; }
        public string payType { get; set; }
    
        public virtual MEMBERLIST MEMBERLIST { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ORDERLIST> ORDERLISTs { get; set; }
        public virtual SHOP SHOP { get; set; }
    }
}
