//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AllShowMVCApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MEMBERLIST
    {
        public MEMBERLIST()
        {
            this.SHOPORDERs = new HashSet<SHOPORDER>();
        }
    
        public int orderNo { get; set; }
        public int memNo { get; set; }
        public Nullable<System.DateTime> orderDate { get; set; }
    
        public virtual MEMBER MEMBER { get; set; }
        public virtual ICollection<SHOPORDER> SHOPORDERs { get; set; }
    }
}
