//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AllShowMVCApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCT
    {
        public PRODUCT()
        {
            this.ORDERLISTs = new HashSet<ORDERLIST>();
        }
    
        public int proNo { get; set; }
        public int shNo { get; set; }
        public int proClassNo { get; set; }
        public string proName { get; set; }
        public double proPrice { get; set; }
        public string proStatement { get; set; }
        public string proState { get; set; }
        public string proPic1 { get; set; }
        public string proPic2 { get; set; }
        public string proPic3 { get; set; }
        public Nullable<System.DateTime> proCreateDate { get; set; }
        public Nullable<System.DateTime> proUpdateDate { get; set; }
        public Nullable<System.DateTime> ProOffShelfDate { get; set; }
        public string proPop { get; set; }
    
        public virtual ICollection<ORDERLIST> ORDERLISTs { get; set; }
        public virtual PRODUCTCLASS PRODUCTCLASS { get; set; }
        public virtual SHOP SHOP { get; set; }
    }
}
